config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #--=== 首頁 ===--#
  root 'welcome#index'

  #--=== 前台 ===--#

  # 商品 #
  resources :products do
    member do
      post :add_to_cart
      post :add_to_wish_list
      post :remove_from_wish_list
      post :setup_currency
    end

    # 搜索 #
    collection do
      get :search
    end
  end

  # 購物車 #
  resources :carts do
    collection do
      delete :clear # 清空購物車
      post :checkout # 下訂
    end
  end

  # 訂單 #
  resources :orders do
    member do
      post :pay_with_paypal # 使用 PayPal 付款
      post :apply_to_cancel # 申請取消訂單
    end
  end

  resources :cart_items

  #--=== 使用者專區 ===--#
  namespace :account do
    # 用戶中心 #
    resources :users
    # 訂單歷程 #
    resources :orders
    # 收藏清單 #
    resources :products do
      member do
        post :add_to_cart
        post :remove_from_wish_list
      end
    end
  end


  #--=== 管理員專區 ===--#
  namespace :admin do

    # 訂單管理 #
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    # 品牌 #
    resources :brands do
      member do
        post :publish
        post :hide
      end
    end


    # 類型 #
    resources :category_groups do
      member do
        post :publish
        post :hide
      end
    end

    # 分類 #
    resources :categories do
      member do
        post :publish
        post :hide
      end
    end

    # 商品 #
    resources :products do
      member do
        post :publish
        post :hide
        post :chosen
      end
    end

    # 首頁 Covers #
    resources :intros do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  # 關聯 #
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  # 加入購物車 #
  def add_product_to_cart(product,quantity)
    ci = cart_items.build
    ci.product = product
    ci.quantity = quantity
    ci.save
  end

  # 修改購物車 #
  def update_product_to_cart(product,quantity)
    ci = cart_items.find_by(product)
    ci.quantity = quantity
    ci.save
  end

  # 清空購物車 #
  def clear!
    cart_items.destroy_all
  end

  # 購物車總價 #
  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # 使用者必須登入
  before_action :authenticate_user!

  def index
    @carts = Cart.all

    # 隨機推薦 3 項商品
    @suggests = Product.published.random3

    # 商品類型 / 品牌
    @category_groups = CategoryGroup.published
    @brands = Brand.published
  end

  # 清空購物車
  def clear
    current_cart.clear!
    flash[:warning] = t('message-clear-cart-success')
    redirect_to carts_path
  end

  # 下訂
  def checkout
    @order = Order.new
  end

end

app/helpers/carts_helper.rb
module CartsHelper
  # 計算購物車商品總價
  def render_cart_total_price(cart)
    if session[:currency].present? # 搜尋幣值數據
      @currency_s = session[:currency]
      @currency = Currency.find_by(name: @currency_s)
      @currency.symbol + " " + cart.total_price.to_s
    else # 預設幣值為新幣
      "SG$ " + cart.total_price.to_s
    end
  end

  # 計算剩餘庫存
  def render_product_quantity(product)
    @product = Product.find(product)
    @orderSum = OrderItem.where("product_id" => product).sum(:quantity)
    @product.quantity - @orderSum
  end
end

app/views/carts/checkout.html.erb
<div class='product-box'>
  <div class='container'>
    <div class='row content-box'>
      <div class='col-md-12'>
        <!--=== 頁面標題 ===-->
        <h3><i class='fa fa-shopping-cart'></i> <%= t('cart-list') %></h3>
        <hr />
        <!--=== 購物車資訊 ===-->
        <div class='row'>
          <!-- 購物車列表內容 -->
            <% current_cart.cart_items.each do |cart_item| %>
            <div class='col-md-12 cart-item-box'>
              <% if cart_item.product.product_images.present? %>
                <!-- 顯示第一張圖片 -->
                <%= image_tag(cart_item.product.product_images[0].image.other.url)%>
              <% else %>
                <%= image_tag('http://placehold.it/200x200&text=No Pic') %>
              <% end %>
              <div class='name'><%= link_to(cart_item.product.name, product_path(cart_item.product)) %></div>
              <div class='price'><%= render_product_price(cart_item.product) %></div>
              <div class='quantity'>x <%= cart_item.quantity %></div>
              <div class='count'>- <%= render_product_price_count(cart_item.product,cart_item.quantity) %></div>
              <hr/>
            </div>
            <% end %>
          </div>
        <br/>
        <!-- 購物車內商品總價 -->
        <div class='clearfix'>
          <div class='pull-right'><%= t('f-cart-total') %> <%= render_cart_total_price(current_cart) %></div>
        </div>

        <hr/>
        <!--=== 訂單資訊 ===-->
        <div class='col-md-6 col-md-offset-3'>
        <h3><i class='fa fa-credit-card'></i> <%= t('checkout-index') %></h3>
          <!--=== 下訂表單 ===-->
          <div class='order-form'>
            <%= simple_form_for @order do |f| %>
              <div class='form-group'>

              <!-- 訂購人 -->
              <legend><%= t('f-billing-info') %></legend>
              <%= f.input :billing_name, placeholder: t('billing-name'), input_html: {value: current_user.name, class: 'width-50'}, :label => t('f-billing-name') %>
              <%= f.input :billing_address, placeholder: t('billing-address'), input_html: {value: current_user.address}, :label => t('f-billing-address') %>

              <hr/>

              <!-- 收貨人 -->
              <legend><%= t('f-shipping-info') %></legend>
              <%= f.input :shipping_name, placeholder: t('shipping-name'), input_html: {value: current_user.name, class: 'width-50'}, :label => t('f-shipping-name') %>
              <%= f.input :shipping_phone, placeholder: t('shipping-phone'), input_html: {value: current_user.phone}, :label => t('f-shipping-phone') %>
              <%= f.input :shipping_address, placeholder: t('shipping-address'), input_html: {value: current_user.address}, :label => t('f-shipping-address') %>

              <hr/>

              <!-- 付款方式 -->
              <legend><%= t('f-payment-method') %></legend>
              <% Order::PAYMENT_METHOD.each do |payment| %>
                <label class="paymant">
                  <%= f.radio_button :payment_method, payment %>
                  <%= t(payment, :scope => 'order.payment_method') %>
                </label>
              <% end %>

              </div>

              <!-- 下訂，產生訂單 -->
              <div class='form-actions'>
                <%= f.submit t('btn-order-create'), class: 'btn btn-md btn-default' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="product-box">
  <div class="container">
    <!--=== 商品類型 & 品牌選單 ===-->
    <%= render "common/menu" %>

    <div class='row content-box'>
        <!--=== 頁面標題 ===-->
        <h3><i class='fa fa-shopping-cart'></i> <%= t('cart-index') %></h3>
        <hr />

        <div class="row">

          <!--=== 如果購物車有商品 ===-->
          <% if current_cart.cart_items.length > 0 %>

              <!--=== 顯示購物車內容 ===-->
              <div class='col-xs-12 col-md-8 cart-item-box'>
                <% current_cart.cart_items.each do |cart_item| %>

                      <!-- 商品圖片 -->
                      <% if cart_item.product.product_images.present? %>
                        <!-- 顯示第一張圖片 -->
                        <%= image_tag(cart_item.product.product_images[0].image.other.url)%>
                      <% else %>
                        <%= image_tag('http://placehold.it/200x200&text=No Pic') %>
                      <% end %>
                      <!-- 商品名稱 -->
                      <div class="name"><%= link_to(cart_item.product.name, product_path(cart_item.product)) %></div>

                    <!-- 商品單價 -->
                    <div class="price"><%= render_product_price(cart_item.product) %></div>
                    <!-- 商品數量 -->
                    <div class="quantity"> x <input type="text" name="quantity" value="<%= cart_item.quantity %>" id="<%= cart_item.product.id %>" max="<%= render_product_quantity(cart_item.product) %>" class="cart-quantity-input"></div>
                    <!-- 商品總價（單錢 x 數量） -->
                    <div class="count"><%= render_product_price_count(cart_item.product,cart_item.quantity) %></div>
                    <!-- 移除單項商品 -->
                    <div class="remove">
                      <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
                        <i class='fa fa-remove'></i>
                      <% end %>
                    </div>

                    <hr/>
                    
                <% end %>
              </div>

              <!--=== 顯示購物車小計、結帳按鈕 ===-->
              <div class='col-xs-12 col-md-4 cart-checkout-box'>

                <!-- 小計、寄送方式 -->
                <div class='clearfix'>
                  <span class='pull-left'><%= t('f-cart-product-count') %></span>
                  <span class='pull-right'><%= render_cart_total_price(current_cart) %></span>
                </div>

                </br>

                <div class='clearfix'>
                  <span class='pull-left'><%= t('f-cart-shipping-fee') %></span>
                  <span class='pull-right'><%= t('f-cart-free-shipping') %></span>
                </div>

                <hr/>

                <!-- 商品總價 -->
                <div class='clearfix'>
                  <span class='pull-left'><%= t('f-cart-total') %></span>
                  <span class='pull-right'><%= render_cart_total_price(current_cart) %></span>
                </div>

                <br/>

                <!-- 購物須知 -->
                <div class='clearfix notice'>
                  <p><%= t('cart-notice') %></p>
                </div>

                <!-- 前往結帳 -->
                <div class='clearfix'>
                  <%= link_to(t('btn-checkout'), checkout_carts_path, method: :post, class: 'btn btn-md btn-default') %>
                </div>
              </div>

          <!--=== 如果購物車沒有商品 ===-->
          <% else %>

            <div class='col-md-12'>
              <div class="buy-box">
                <h3><%= t('cart-no-data') %></h3>
                <h3><%= t('cart-suggest') %></h3>
                <br/>
                <!-- 隨機推薦商品 -->
                <div class='col-md-8 col-md-offset-2'>
                  <%= render "shared/suggest" %>
                </div>
                <div class='col-md-12'>
                  <%= link_to(t('btn-buy-now'), products_path, class:'btn btn-lg btn-default' ) %>
                </div>
              </div>
            </div>

          <% end %>

        </div>
    </div>
  </div>
</div>