config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #--=== 首頁 ===--#
  root 'welcome#index'

  #--=== 前台 ===--#

  # 商品 #
  resources :products do
    member do
      post :add_to_cart
      post :add_to_wish_list
      post :remove_from_wish_list
      post :setup_currency
    end

    # 搜索 #
    collection do
      get :search
    end
  end

  # 購物車 #
  resources :carts do
    collection do
      delete :clear # 清空購物車
      post :checkout # 下訂
    end
  end

  # 訂單 #
  resources :orders do
    member do
      post :pay_with_paypal # 使用 PayPal 付款
      post :apply_to_cancel # 申請取消訂單
    end
  end

  resources :cart_items

  #--=== 使用者專區 ===--#
  namespace :account do
    # 用戶中心 #
    resources :users
    # 訂單歷程 #
    resources :orders
    # 收藏清單 #
    resources :products do
      member do
        post :add_to_cart
        post :remove_from_wish_list
      end
    end
  end


  #--=== 管理員專區 ===--#
  namespace :admin do

    # 訂單管理 #
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    # 品牌 #
    resources :brands do
      member do
        post :publish
        post :hide
      end
    end


    # 類型 #
    resources :category_groups do
      member do
        post :publish
        post :hide
      end
    end

    # 分類 #
    resources :categories do
      member do
        post :publish
        post :hide
      end
    end

    # 商品 #
    resources :products do
      member do
        post :publish
        post :hide
        post :chosen
      end
    end

    # 首頁 Covers #
    resources :intros do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # 新增/修改欄位限制與提示 #
  validates :name, presence: { message: "請輸入分類名稱" }
  validates :category_group_id, presence: { message: "請選擇分類類型" }

  # 關聯 #
  belongs_to :category_group
  has_many :products

  # 發佈 / 隱藏 #
  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  # 上傳分類 Logo 圖 #
  mount_uploader :logo, ImageUploader

  # Scope #
  scope :published, -> { where(is_hidden: false) }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  # 使用者必須登入
  before_action :authenticate_user!
  # 使用者必須是 admin 身份
  before_action :admin_required
  # 後台頁面排版
  layout "admin"

  def index
    @categories = Category.all
    @category_groups = CategoryGroup.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
    # 所屬的大分類
    @category_groups = CategoryGroup.all
    # @category_groups = CategoryGroup.all.map { |g| [g.name, g.id] }
  end

  def create
    @category = Category.new(category_params)
    # 所屬的大分類
    # @category_groups = CategoryGroup.all.map { |g| [g.name, g.id] }
    # @category.category_group_id = params[:category_group_id]

    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    # 所屬的大分類
    @category_groups = CategoryGroup.all
    # @category_groups = CategoryGroup.all.map { |g| [g.name, g.id] }
  end

  def update
    @category = Category.find(params[:id])
    # 所屬的大分類
    # @category_groups = CategoryGroup.all.map { |g| [g.name, g.id] }
    # @category.category_group_id = params[:category_group_id]

    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  # 發佈
  def publish
    @category = Category.find(params[:id])
    @category.publish!
    redirect_to :back
  end

  # 隱藏
  def hide
    @category = Category.find(params[:id])
    @category.hide!
    redirect_to :back
  end

  private

  def category_params
    params.require(:category).permit(:name, :category_group_id, :is_hidden, :description, :logo)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
  # 判斷分類隱藏狀態，顯示 Public/Hidden 狀態
  def render_category_status(category)
    if category.is_hidden
      content_tag(:span, "", :class => "fa fa-lock fa-fw")
    else
      content_tag(:span, "", :class => "fa fa-globe fa-fw")
    end
  end

  # 判斷分類隱藏狀態，顯示 Publish/Hide 按鈕
  def render_category_publish_or_hide(category)
    if category.is_hidden
      link_to(t('btn-publish'), publish_admin_category_path(category), :method => :post, :class => 'btn btn-sm btn-default')
    else
      link_to(t('btn-hide'), hide_admin_category_path(category), :method => :post, :class => 'btn btn-sm btn-default')
    end
  end
end

app/views/admin/categories/_form.html.erb
<div class="col-md-8 col-md-offset-2 admin-data-box">
  <hr style="size:2px" />
  <%= simple_form_for [:admin, @category] do |f| %>
    <%= f.input :category_group_id, :label => t('f-category-groups'), :collection => @category_groups, input_html: { class: 'width-50' } %>
    <%= f.input :name, :label => t('f-category-name') %>
    <span class="hidden-box"><%= f.input :is_hidden, :label => t('f-hide') %></span>
    <div class="form-actions">
      <%= f.submit t('f-submit'), class: 'btn btn-md btn-default' %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<!--=== 修改分類 ===-->
<h2><span class="fa fa-pencil-square-o"></span> <%= t('category-edit') %></h2>
<%= render('form') %>

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!--=== 頁面標題 ===-->
    <h2><%= t('category-group-index') %></h2>

    <!--=== 新增類型 ===-->
    <div class="pull-right">
      <%= link_to(t('btn-category-group-new'), new_admin_category_group_path, :class => 'btn btn-md btn-info')%>
    </div>

    <!--=== 類型列表 ===-->
    <table class="table">
      <!--=== 類型列表標題 ===-->
      <thead>
        <tr>
          <th><%= t('f-category-group') %></th>
          <th class="pull-right"><%= t('f-options') %></th>
        </tr>
      </thead>
      <!--=== 類型列表內容 ===-->
      <% @category_groups.each do |category_group| %>
        <tr>
          <td><%= render_category_group_status(category_group) %> <%= category_group.name %></td>
          <!--=== 操作選項 ===-->
          <td class="action-box pull-right">
            <%= link_to(edit_admin_category_group_path(category_group), class: "btn btn-md btn-default") do %>
              <span class="fa fa-pencil"></span>
            <% end %>

            <!-- 發佈 / 隱藏 -->
            <!-- <%= render_category_group_publish_or_hide(category_group) %> -->
            <% if category_group.is_hidden %>
              <%= link_to(publish_admin_category_group_path(category_group), :method => :post, class: "btn btn-md btn-default show-btn") do %>
                <span class="fa fa-eye"></span>
              <% end %>
            <% else %>
              <%= link_to(hide_admin_category_group_path(category_group), :method => :post, data: { confirm: "確定隱藏該類型？" }, class: "btn btn-md btn-default") do %>
                <span class="fa fa-eye-slash"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>

    <!--=== 頁面標題 ===-->
    <h2><%= t('category-index') %></h2>

    <!--=== 新增分類 ===-->
    <div class="pull-right">
      <%= link_to(t('btn-category-new'), new_admin_category_path, :class => 'btn btn-md btn-info')%>
    </div>

    <!--=== 分類列表 ===-->
    <table class="table">
      <!--=== 分類列表標題 ===-->
      <thead>
        <tr>
          <th><%= t('f-category-group') %></th>
          <th><%= t('f-category-name') %></th>
          <th class="pull-right"><%= t('f-options') %></th>
        </tr>
      </thead>

      <!--=== 分類列表內容 ===-->
      <% @categories.each do |category| %>
        <tr>
          <td><%= render_category_status(category) %> <%= category.category_group.name %></td>
          <td><%= link_to(category.name, admin_category_path(category)) %></td>
          <!--=== 操作選項 ===-->
          <td class="action-box pull-right">
            <%= link_to(edit_admin_category_path(category), class: "btn btn-md btn-default") do %>
              <span class="fa fa-pencil"></span>
            <% end %>

            <!-- 發佈 / 隱藏 -->
            <!-- <%= render_category_publish_or_hide(category) %> -->
            <% if category.is_hidden %>
              <%= link_to(publish_admin_category_path(category), :method => :post, class: "btn btn-md btn-default show-btn") do %>
                <span class="fa fa-eye"></span>
              <% end %>
            <% else %>
              <%= link_to(hide_admin_category_path(category), :method => :post, data: { confirm: "確定隱藏該分類？" }, class: "btn btn-md btn-default") do %>
                <span class="fa fa-eye-slash"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/categories/new.html.erb
<!--=== 新增分類 ===-->
<h2><span class="fa fa-file-text-o"></span> <%= t('category-new') %></h2>
<%= render('form') %>

app/views/admin/categories/show.html.erb
<!--=== 分類資訊 ===-->
<h1> <%= @category.name %> </h1>

<!-- 所屬主類別 -->
<h3><%= t('f-category-group') %></h3>
<%= @category.category_group.name %>

<!-- 該分類下的商品一覽 -->
<h3><%= t('f-category-products') %></h3>
<% @category.products.each do |product| %>
  <li><%= link_to(product.name, admin_product_path(product)) %></li>
<% end %>