config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #--=== 首頁 ===--#
  root 'welcome#index'

  #--=== 前台 ===--#

  # 商品 #
  resources :products do
    member do
      post :add_to_cart
      post :add_to_wish_list
      post :remove_from_wish_list
      post :setup_currency
    end

    # 搜索 #
    collection do
      get :search
    end
  end

  # 購物車 #
  resources :carts do
    collection do
      delete :clear # 清空購物車
      post :checkout # 下訂
    end
  end

  # 訂單 #
  resources :orders do
    member do
      post :pay_with_paypal # 使用 PayPal 付款
      post :apply_to_cancel # 申請取消訂單
    end
  end

  resources :cart_items

  #--=== 使用者專區 ===--#
  namespace :account do
    # 用戶中心 #
    resources :users
    # 訂單歷程 #
    resources :orders
    # 收藏清單 #
    resources :products do
      member do
        post :add_to_cart
        post :remove_from_wish_list
      end
    end
  end


  #--=== 管理員專區 ===--#
  namespace :admin do

    # 訂單管理 #
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    # 品牌 #
    resources :brands do
      member do
        post :publish
        post :hide
      end
    end


    # 類型 #
    resources :category_groups do
      member do
        post :publish
        post :hide
      end
    end

    # 分類 #
    resources :categories do
      member do
        post :publish
        post :hide
      end
    end

    # 商品 #
    resources :products do
      member do
        post :publish
        post :hide
        post :chosen
      end
    end

    # 首頁 Covers #
    resources :intros do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # 新增/修改欄位限制與提示 #
  validates :name, presence: { message: "請輸入商品名稱" }
  validates :price, presence: { message: "請輸入商品售價" }
  validates :price, numericality: { greater_than: 0, message: "請輸入商品售價，必須大於零" }
  validates :quantity, presence: { message: "請入庫存數量" }, numericality: { greater_than_or_equal: 0 }
  validates :category_id, presence: { message: "請選擇商品分類" }
  validates :brand_id, presence: { message: "請選擇商品品牌" }

  # 關聯 #
  belongs_to :category
  belongs_to :brand
  has_one :order_item

  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images

  has_many :wish_lists
  has_many :wish_list_owners, :through => :wish_lists, :source => :user

  has_many :product_color_relationships
  has_many :colors, :through => :product_color_relationships, :source => :color
  accepts_nested_attributes_for :colors

  # 商品資訊網址優化 #
  def to_param
    "#{self.id}-#{self.name.gsub(/\s+/, "")}"
  end

  # 發佈 / 隱藏 #
  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  # 精選商品 #
  def chosen!
    self.is_chosen = true
    self.save
  end

  def no_chosen!
    self.is_chosen = false
    self.save
  end

  # 檢查 is_hidden 的 boolean 值 #
  def hidden?
    is_hidden
  end

  # Scope #
  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }
  scope :random3, -> { limit(3).order('RANDOM()') }

end

app/controllers/account/products_controller.rb
class Account::ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = current_user.wish_list_items

    # 隨機推薦 3 項商品
    @suggests = Product.published.random3

    # 商品類型 / 品牌
    @category_groups = CategoryGroup.published
    @brands = Brand.published
  end

  # 從願望清單上刪除該商品
  def remove_from_wish_list
    @product = Product.find(params[:id])
    if current_user.is_wish_list_owner_of?(@product)
      current_user.remove_from_wish_list!(@product)
    end

    redirect_to :back
  end

  # 移動至購物車
  def add_to_cart
    @product = Product.find(params[:id])
    @quantity = 1

    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product,@quantity)
      current_user.remove_from_wish_list!(@product)
      flash[:notice] = t('message-add-to-cart-success')
    else
      flash[:warning] = t('message-already-added')
    end

    redirect_to :back
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # 使用者必須登入
  before_action :authenticate_user!
  # 使用者必須是 admin 身份
  before_action :admin_required
  # 後台頁面排版
  layout "admin"

  def index
    @products = Product.all.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @product = Product.find(params[:id])

    # 商品圖片
    @product_images = @product.product_images.all
  end

  def new
    @product = Product.new

    # 商品圖片
    @product_image = @product.product_images.build

    # 商品所屬的品牌/分類/顏色
    @brands = Brand.all
    @categories = Category.all.order("category_group_id, name")
    @colors = Color.all

  end

  def create
    @product = Product.new(product_params)

    if @product.save
      if params[:product_images] != nil
        params[:product_images]['image'].each do |i|
          @product_image = @product.product_images.create(:image => i)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])

    # 商品所屬的品牌/分類
    @brands = Brand.all
    @categories = Category.all.order("category_group_id, name")

  end

  def update
    @product = Product.find(params[:id])

    # 商品圖片
    if params[:product_images] != nil
      #刪除舊圖
      @product.product_images.destroy_all

      params[:product_images]['image'].each do |i|
        @product_image = @product.product_images.create(:image => i)
      end
      @product.update(product_params)

    elsif @product.update(product_params)
      redirect_to admin_products_path and return
    else
      render :edit

    end

    # 商品所屬的品牌
    @brands = Brand.all.map { |b| [b.name, b.id] }
    @product.brand_id = params[:brand_id]
    # 產品所屬的分類
    @categories = Category.all.map { |c| [c.name, c.id] }
    @product.category_id = params[:category_id]

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  # 發佈
  def publish
    @product = Product.find(params[:id])
    @product.publish!
    redirect_to :back
  end

  # 隱藏
  def hide
    @product = Product.find(params[:id])
    @product.hide!
    redirect_to :back
  end

  # 精選商品
  def chosen
    @product = Product.find(params[:id])
    if @product.is_chosen == true
      @product.no_chosen!
    else
      @product.chosen!
    end

    redirect_to :back
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :category_id, :brand_id, :size, :material, :country, :is_hidden, :is_chosen, color_ids: [])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:add_to_wish_list, :remove_from_wish_list]
  before_action :validate_search_key, only: [:search]

  def index
    # 商品類型 / 品牌
    @category_groups = CategoryGroup.published
    @brands = Brand.published

    # 判斷是否篩選分類
    if params[:category].present?
      @category_s = params[:category]
      @category = Category.find_by(name: @category_s)

      @products = Product.where(:category => @category.id).published.recent.paginate(:page => params[:page], :per_page => 12)

    # 判斷是否篩選類型
    elsif params[:group].present?
      @group_s = params[:group]
      @group = CategoryGroup.find_by(name: @group_s)

      @products = Product.joins(:category).where("categories.category_group_id" => @group.id).published.recent.paginate(:page => params[:page], :per_page => 12)

    # 判斷是否篩選品牌
    elsif params[:brand].present?
      @brand_s = params[:brand]
      @brand = Brand.find_by(name: @brand_s)

      @products = Product.where(:brand => @brand.id).published.recent.paginate(:page => params[:page], :per_page => 12)

    # 判斷是否選擇精選商品
    elsif params[:chosen].present?
      @products = Product.where(:is_chosen => true).published.recent.paginate(:page => params[:page], :per_page => 12)

    # 預設顯示所有公開商品
    else
      @products = Product.published.recent.paginate(:page => params[:page], :per_page => 12)
    end
  end

  def show
    @product = Product.find(params[:id])
    @product_images = @product.product_images.all
    @orderSum = OrderItem.where("product_id" => @product.id).sum(:quantity)
    @product_stock = @product.quantity - @orderSum

    # 隨機推薦 3 項商品
    @suggests = Product.published.random3

    # 類型 / 品牌 / 幣值
    @category_groups = CategoryGroup.published
    @brands = Brand.published
    @currencies = Currency.all

    set_page_title       @product.name
    set_page_description @product.description
    set_page_keywords    @product.name
    set_page_image       @product_images.first.image.main.url
  end

  # 設定幣值
  def setup_currency
    set_currency

    redirect_to :back
  end

  # 加入購物車
  def add_to_cart
    @product = Product.find(params[:id])
    @quantity = params[:quantity]

    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product,@quantity)
      flash[:notice] = t('message-add-to-cart-success')
    else
      flash[:warning] = t('message-already-added')
    end

    redirect_to :back
  end

  # 將該商品加入願望清單
  def add_to_wish_list
    @product = Product.find(params[:id])
    if !current_user.is_wish_list_owner_of?(@product)
      current_user.add_to_wish_list!(@product)
    end

    redirect_to :back
  end

  # 從願望清單上刪除該商品
  def remove_from_wish_list
    @product = Product.find(params[:id])
    if current_user.is_wish_list_owner_of?(@product)
      current_user.remove_from_wish_list!(@product)
    end

    redirect_to :back
  end

  def search
    if @query_string.present?
      # 顯示符合條件的商品
      search_result = Product.joins(:brand).ransack(@search_criteria).result(:distinct => true)
      @products = search_result.published.recent.paginate(:page => params[:page], :per_page => 12 )
    end

    @category_groups = CategoryGroup.published
    @brands = Brand.published
  end

  protected

  def validate_search_key
    # 去除特殊字符
    @query_string = params[:keyword].gsub(/\\|\'|\/|\?/, "") if params[:keyword].present?
    @search_criteria = search_criteria(@query_string)

  end

  def search_criteria(query_string)
    # 篩選多個欄位
    { :name_or_description_or_brand_name_cont => query_string }
  end

end

app/helpers/account/products_helper.rb
module Account::ProductsHelper
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  # 判斷產品隱藏狀態，顯示 Public/Hidden 狀態
  def render_product_status(product)
    if product.is_hidden
      content_tag(:span, "", :class => "fa fa-lock fa-fw")
    else
      content_tag(:span, "", :class => "fa fa-globe fa-fw")
    end
  end

  # 判斷產品是否為精選商品
  def render_product_chosen_status(product)
    if product.is_chosen
      content_tag(:span, "", :class => "fa fa-heart fa-fw")
    end
  end

  # 判斷產品隱藏狀態，顯示 Publish/Hide 按鈕
  def render_product_publish_or_hide(product)
    if product.is_hidden
      link_to(t('btn-publish'), publish_admin_product_path(product), :method => :post, :class => 'btn btn-sm btn-default')
    else
      link_to(t('btn-hide'), hide_admin_product_path(product), :method => :post, :class => 'btn btn-sm btn-default')
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  # 幣值切換
  def render_product_price(product)
    if session[:currency].present?
      @currency_s = session[:currency]
      @currency = Currency.find_by(name: @currency_s)
      product.price = product.price * @currency.rate
      price = @currency.symbol + " " + product.price.to_s
    else # 預設幣值為新幣
      price = "SG$ " + product.price.to_s
    end
  end
end

app/views/products/_currency.html.erb
<!--=== 幣值切換 ===-->
<div class='dropdown btn-group clearfix'>
  <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
    <%= t('nav-currency') %> <i class="fa fa-angle-down"></i>
  </button>
  <!-- 下拉式選單 -->
  <ul class='dropdown-menu dropdown-menu-right'>
    <!-- 選單列出所有幣值 -->
    <% @currencies.each do |currency| %>
      <li>
        <%= link_to setup_currency_product_path(:currency => currency.name), method: :post, :remote => true do %>
          <%= currency.symbol %> - <%= currency.name %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/products/_menu.html.erb
<!--=== 商品類型 & 品牌選單 ===-->
<div class="btn-group">

  <!--=== 精選商品 ===-->
  <div class='dropdown btn-group clearfix'>
    <%= link_to products_path(:chosen => 'y'), class: 'btn' do %>
      <%= t('f-product-chosen') %> #
    <% end %>
  </div>

  <!--=== 類型選單 ===-->
  <% @category_groups.each do |category_group| %>
    <div class='dropdown btn-group clearfix'>
      <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
        <%= category_group.name %> <i class="fa fa-angle-down"></i>
      </button>

      <!-- 選項：列出該類型所有分類 -->
      <ul class='dropdown-menu'>
        <% category_group.categories.each do |category| %>
          <li>
            <%= link_to(category.name, products_path(:category => category.name)) %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--=== 品牌選單 ===-->
  <div class='dropdown btn-group clearfix'>
    <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
      <%= t('nav-brand') %> <i class="fa fa-angle-down"></i>
    </button>

    <!-- 選項：列出所有品牌 -->
    <ul class='dropdown-menu'>
      <% @brands.each do|brand| %>
        <li>
          <%= link_to(brand.name, products_path(:brand => brand.name)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<hr/>

<div class="path-box">
  <!--=== 產品頁面路徑 ===-->
  <div class="left-box">
    <%= link_to products_path do %>
      <%= (t('j-and-z-select')) %>
    <% end %>

    <% if params[:id].present? %>
    / <a href="../products?group=<%= @product.category.category_group.name %>"><%= @product.category.category_group.name %></a> / <a href="../products?category=<%= @product.category.name %>"><%= @product.category.name %></a> / <a href="<%= @product.id %>"><%= @product.name %></a>
    <% elsif params[:category].present? %>
    / <a href="products?group=<%= @category.category_group.name %>"><%= @category.category_group.name %></a> / <a href="products?category=<%= @category.name %>"><%= @category.name %></a>
    <% elsif params[:group].present? %>
    / <a href="products?group=<%= @group.name %>"><%= @group.name %></a>
    <% elsif params[:brand].present? %>
    / <a href="products?brand=<%= @brand.name %>"><%= @brand.name %></a>
    <% elsif params[:chosen].present? %>
    / <a href="products?chosen=y"><%= t('f-product-chosen') %></a>
    <% end %>
  </div>

  <!-- 只在 Products#index 和 products/search 兩個頁面顯示 -->
  <% if current_page?(products_url) || current_page?('/products/search') %>
  <!--=== 排序選單 ===-->
  <div class="right-box">
    <div class="dropdown btn-group clearfix">
      <% if params[:order].present? %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= params[:order] %> <span class="caret"></span>
        </button>
      <% else %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= t('order-btn-title') %> <span class="caret"></span>
        </button>
      <% end %>

      <!-- 選項：列出排序方式 -->
      <ul class="dropdown-menu dropdown-menu-right" selection aria-labelledby="dropdownMenuDivider">
        <li><%= link_to(t('order-btn-hot'), '#') %></li>
        <li><%= link_to(t('order-btn-recent'), '#') %></li>
        <li><%= link_to(t('order-btn-price-l'), '#') %></li>
        <li><%= link_to(t('order-btn-price-h'), '#') %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>
<hr/>

app/views/products/_specification.html.erb
<!-- 商品規格：尺寸 / 材質 / 產地 -->

<% if @product.size.present? %>
<p>
  <%= t('product-size') %>：<%= @product.size %>
</p>
<% end %>

<% if @product.material.present? %>
<p>
  <%= t('product-material') %>：<%= @product.material %>
</p>
<% end %>

<% if @product.country.present? %>
  <p>
    <%= t('product-country') %>：<%= @product.country %>
  </p>
<% end %>

<div class='color-circle'>
  <% if @product.colors.present? %>
    <p>
      <%= t('product-color') %>：
      <% @product.colors. each do |color|%>
          <button style='background-color:<%= color.code %>'></button>
      <% end %>
    </p>
  <% end %>
</div>

app/views/products/index.html.erb
<div class="product-box">
  <div class="container">
  <!--=== 商品類型 Banner ===-->
  <% if params[:id].present? %>
    <%= image_tag(@product.category.category_group.image, class: "background-image") %>
  <% elsif params[:category].present? %>
    <%= image_tag(@category.category_group.image, class: "background-image") %>
  <% elsif params[:group].present? %>
    <%= image_tag(@group.image, class: "background-image") %>
  <% else %>
    <%= image_tag("product_bg.jpg", class: "background-image") %>
  <% end %>
  <!--=== 商品類型 & 品牌選單 ===-->
  <%= render "products/menu" %>

  <% if @products.length > 0 %>
    <!--=== 商品列表 ===-->
    <div class='row'>
      <% @products.each_with_index do |product, index| %>
        <div class='col-xs-12 col-sm-4 col-md-3 product-content'>
          <%= link_to product_path(product) do %>
            <!-- 商品圖片 -->
            <% if product.product_images.present? %>
              <!-- 顯示第一張圖片 -->
              <% if product.is_chosen %>
                <div class="chosen-box"><%= t('product-chosen') %></div>
              <% end %>
              <%= image_tag(product.product_images[0].image.other.url, class: 'thumbnail')%>
            <% else %>
              <%= image_tag('http://placehold.it/200x200&text=No Pic', class: 'thumbnail') %>
            <% end %>
          <% end %>
          <div class="product-info">
            <p><%= link_to(product.name , product_path(product)) %></p>
            <p><%= render_product_price(product) %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="product-content">
      <h2><%= (t('no-product-data')) %></h2>
    </div>
  <% end %>

    <div class="page-box">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails, :previous_label => t('previous-label'), :next_label => t('next-label') %>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<div class="product-box">
  <div class="container">
    <%= image_tag("product_bg.jpg", class: "background-image") %>
    <%= render "products/menu" %>
    <!--=== 搜索结果，没有符合条件的数据 ===-->
    <% if @products.blank?%>
      <div class="search-error">
        <h2><%= t('search-no-data')%></h2>
      </div>
    <% else %>
    <!--=== 搜索结果，有符合条件的数据 ===-->
    <!--=== 搜索內容 ===-->
      <div class='row'>
        <% @products.each do |product| %>
          <div class='col-xs-12 col-sm-4 col-md-3 product-content'>
            <%= link_to product_path(product) do %>
              <!-- 商品圖片 -->
              <% if product.product_images.present? %>
                <!-- 顯示第一張圖片 -->
                <%= image_tag(product.product_images[0].image.other.url, class: 'thumbnail')%>
              <% else %>
                <%= image_tag('http://placehold.it/200x200&text=No Pic', class: 'thumbnail') %>
              <% end %>
            <% end %>
            <div class="product-info">
              <p><%= link_to(product.name , product_path(product)) %></p>
              <p>SG$ <%= product.price %></p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="page-box">
        <%= will_paginate @products, renderer: BootstrapPagination::Rails, :previous_label => t('previous-label'), :next_label => t('next-label') %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class='product-box product-show'>
  <div class='container'>
    <!--=== 商品類型 & 品牌選單 ===-->
    <%= image_tag(@product.category.category_group.image, class: 'background-image') %>
    <%= render 'products/menu' %>

    <!-- 如果商品是上架狀態 -->
    <% if !@product.hidden?  %>

        <!-- 商品圖片 -->
        <div class='col-xs-12 col-md-8 product-image'>
          <div class='row'>
            <% if @product_images.present? %>
            <!-- 顯示第一張商品圖片 - main 尺寸大圖 -->
            <div class='col-md-12'>
              <% if @product.is_chosen %>
                <div class="chosen-box location"><%= t('product-chosen') %></div>
              <% end %>
              <%= image_tag(@product_images.first.image.main.url, class: 'main-image thumbnail') %>
            </div>
              <% @product_images.each_with_index do |p| %>
                <!-- 顯示所有商品圖片 - other 尺寸小圖 -->
                <div class='col-md-2 col-sm-4 col-xs-6 image-box'>
                  <%= image_tag(p.image.other.url, class: 'list-image thumbnail') %>
                </div>
              <% end %>
            <% else %>
              <%= image_tag('http://placehold.it/400x400&text=No Pic', class: 'thumbnail') %>
            <% end %>
          </div>
        </div>
        <!--=== 商品資訊 ===-->
        <%= form_tag add_to_cart_product_path(@product), :method => :post, :remote => true do %>
        <div class='col-xs-12 col-md-4 product-detail'>
          <div>
            <h1><%= @product.name %></h1>
            <div class="price">
              <div class="left-box">
                <h3><%= render_product_price(@product) %></h3>
              </div>
              <div class="right-box currency">
                <!-- 幣值轉換 -->
                <%= render 'products/currency' %>
              </div>
            </div>
            <p><%= simple_format(@product.description) %></p>
          </div>
          <hr />
          <div>
            <p><%= t('product-brand') %>：<%= link_to(@product.brand.name, products_path(:brand => @product.brand.name)) %></p>
            <!-- 商品規格：尺寸 / 材質 / 產地 / 顏色 -->
            <%= render 'products/specification' %>
            <br/>
            <p>
              <!--=== 如果庫存數量大於零 ===-->
              <% if @orderSum < @product.quantity && @product.quantity > 0 %>
              <div class="quantity-box">
                <div class="left-box"><%= t('product-quantity') %>：</div>
                <div class="left-box quantity-button">
                  <%= link_to("-", "", id: "quantity-down", class: "quantity-actions") %>
                  <input type="text" name="quantity" value="1" id="quantity" max="<%= @product.quantity - @orderSum %>" class="quantity-input">
                  <%= link_to("+", "", id: "quantity-up", class: "quantity-actions") %>
                </div>
                <% if @product_stock <= 10 %>
                <span class="quantity-stock">(库存数量：<%= @product_stock %>)</span>
                <% end %>
              </div>

              <!--=== 如果沒有庫存 ===-->
              <% else %>
                <div class="quantity-box">
                  <%= t('product-quantity') %>：<span class="quantity-none"><%= t('product-quantity-none') %></span>
                </div>
              <% end %>
            </p>

          </div>
          <hr />

          <div class='row'>
            <!-- 願望清單 -->
            <div class='left-box wish'>
              <% if current_user && current_user.is_wish_list_owner_of?(@product) %>
                <%= link_to remove_from_wish_list_product_path(@product), method: :post do %>
                  <i class='fa fa-check fa-fw'> </i><%= t('wish-list-remove') %>
                <% end %>
              <% else %>
                <%= link_to add_to_wish_list_product_path(@product), method: :post do %>
                  <i class='fa fa-plus fa-fw'> </i><%= t('wish-list-add') %>
                <% end %>
              <% end %>
            </div>
            <div class='right-box share'>
              <%= social_share_button_tag(@product.name, :allow_sites => %w(facebook twitter google_plus wechat weibo), :image => @product_images.first.image.main.url , desc: @product.description, via: 'J&Z SELECT - '+@product.name, 'data-twitter-title' => 'J&Z SELECT - '+@product.name) %>
            </div>
          </div>
          <!--=== 如果庫存數量大於零 ===-->
          <% if @orderSum < @product.quantity && @product.quantity > 0 %>
            <!-- 加入購物車 -->
            <button class="btn btn-md btn-default" type="submit">
              <%= t('btn-add-to-cart')%>
            </button>

          <!--=== 如果沒有庫存 ===-->
          <% else %>
            <button class="btn btn-md btn-default" disabled="disabled" type="button">
              <%= t('btn-add-to-cart-none')%>
            </button>
          <% end %>
          <!-- 顯示隨機推薦商品 -->
          <div class='suggest-box'>
            <hr class='suggest'>
            <%= render 'shared/suggest' %>
          </div>
        </div>
        <% end %>

    <!-- 如果商品是隱藏狀態 -->
    <% else %>

      <div class='buy-box'>
        <h1><%= t('product-is-hidden') %></h1>
        <br/>
        <%= link_to(t('btn-continue'), products_path, class:'btn btn-lg btn-default' ) %>
      </div>

    <% end %>

  </div>
</div>