config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #--=== 首頁 ===--#
  root 'welcome#index'

  #--=== 前台 ===--#

  # 商品 #
  resources :products do
    member do
      post :add_to_cart
      post :add_to_wish_list
      post :remove_from_wish_list
      post :setup_currency
    end

    # 搜索 #
    collection do
      get :search
    end
  end

  # 購物車 #
  resources :carts do
    collection do
      delete :clear # 清空購物車
      post :checkout # 下訂
    end
  end

  # 訂單 #
  resources :orders do
    member do
      post :pay_with_paypal # 使用 PayPal 付款
      post :apply_to_cancel # 申請取消訂單
    end
  end

  resources :cart_items

  #--=== 使用者專區 ===--#
  namespace :account do
    # 用戶中心 #
    resources :users
    # 訂單歷程 #
    resources :orders
    # 收藏清單 #
    resources :products do
      member do
        post :add_to_cart
        post :remove_from_wish_list
      end
    end
  end


  #--=== 管理員專區 ===--#
  namespace :admin do

    # 訂單管理 #
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    # 品牌 #
    resources :brands do
      member do
        post :publish
        post :hide
      end
    end


    # 類型 #
    resources :category_groups do
      member do
        post :publish
        post :hide
      end
    end

    # 分類 #
    resources :categories do
      member do
        post :publish
        post :hide
      end
    end

    # 商品 #
    resources :products do
      member do
        post :publish
        post :hide
        post :chosen
      end
    end

    # 首頁 Covers #
    resources :intros do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <!--=== 關閉鍵 ===-->
      <button class="close" data-dismiss="alert">×</button>
      <!--=== 讀取提示訊息 ===-->
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-md-2 col-xs-4">
            <h4><%= t('th-products') %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= t('link-latest') %></a></li>
              <li><a href="#s"><%= t('link-exclusive') %></a></li>
              <li><a href="#s"><%= t('link-brands') %></a></li>
            </ul>
          </div>
          <div class="col-md-2 col-xs-4">
            <h4><%= t('th-service-info') %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= t('link-shipping') %></a></li>
              <li><a href="#s"><%= t('link-return') %></a></li>
              <li><a href="#s"><%= t('link-faq') %></a></li>
            </ul>
          </div>
          <div class="col-md-2 col-xs-4">
            <h4><%= t('th-about-us') %></h4>
            <ul class="list-unstyled">
              <li><a href="#s"><%= t('link-story') %></a></li>
              <li><a href="#s"><%= t('link-media') %></a></li>
              <li><a href="#s"><%= t('link-contact') %></a></li>
            </ul>
          </div>
          <div class="col-md-6 col-xs-12">
            <br/>
            <h4><%= image_tag("logo.png") %><%= t('j-and-z-select') %></h4>
            <ul class="list-unstyled">
              <p>Designed By <a href="https://github.com/lbias/robot-store" target="_blank">lbias</a> 
              <br/>
              Copyright ©2017 J&Z SELECT</a>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/common/_menu.html.erb
<%= image_tag("product_bg.jpg", class: "background-image") %>
<!--=== 商品類型 & 品牌選單 ===-->
<div class="btn-group">
  <!--=== 類型 ===-->
  <% @category_groups.each do |category_group| %>
    <div class='dropdown btn-group clearfix'>
      <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
        <%= category_group.name %> <i class="fa fa-angle-down"></i>
      </button>
      <!-- 下拉式選單 -->
      <ul class='dropdown-menu'>
        <!-- 選單列出該類型所有分類 -->
        <% category_group.categories.each do |category| %>
          <li>
            <%= link_to(category.name, products_path(:category => category.name)) %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--=== 品牌 ===-->
  <div class='dropdown btn-group clearfix'>
    <button class='btn dropdown-toggle' type='button' data-toggle='dropdown'>
      <%= t('nav-brand') %> <i class="fa fa-angle-down"></i>
    </button>
    <!-- 下拉式選單 -->
    <ul class='dropdown-menu'>
      <!-- 選單列出所有品牌 -->
      <% @brands.each do|brand| %>
        <li>
          <%= link_to(brand.name, products_path(:brand => brand.name)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<hr/>

app/views/common/_navbar.html.erb
<div class="row">
  <div class="col-md-12">
    <% if current_page?('/') %>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
    <% else %>
      <div class="navbar navbar-default navbar-fixed-top show_bgcolor" role="navigation">
    <% end %>
      <div class="container">
        <div class="navbar-header">
          <!--=== 右側下拉選單（移動端顯示） ===-->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-4" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--=== 網站 Logo/名稱 ===-->
          <%= link_to root_path, class: "navbar-brand logo-box scroll" do %>
            <%= image_tag("logo.png") %><%= t('j-and-z-select') %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse top-nav" id="menu-4">
          <!--=== 網站連結 ===-->
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to(t('product-access'), products_path) %></li>
            <!-- <li><%= link_to(t('brand-access'), '#', class: "scroll") %></li>
            <li><%= link_to(t('recommend-access'), '#', class: "scroll") %></li> -->
          </ul>
          <!--=== 帳號操作 ===-->
          <ul class='nav navbar-nav  navbar-right'>
            <li class="divider" role="separator"></li>
            <!-- 願望清單 -->
            <li>
              <%= link_to account_products_path do %>
                <%= t('wish-list') %> <i class='fa fa-gift'></i>
              <% end %>
            </li>
            <!-- 購物車 -->
            <li>
              <%= link_to carts_path do %>
                <i class='fa fa-shopping-cart'></i> ( <%= current_cart.products.count %> )
              <% end %>
            </li>
            <!-- 切換語系 -->
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= t('language') %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <!-- 語系選項 -->
                <li><%= link_to "简体中文", :controller => controller_name, :action => action_name, :locale => "zh-CN" %></li>
                <li><%= link_to "繁體中文", :controller => controller_name, :action => action_name, :locale => "zh-TW" %></li>
                <li><%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %></li>
              </ul>
            </li>
            <% if !current_user %>
              <!-- 訪客註冊 / 登入 -->
              <li><%= link_to(t('signup'), new_user_registration_path) %> </li>
              <li><%= link_to(t('login'), new_user_session_path) %></li>
            <% else %>
              <!-- 使用者下拉式選單 -->
              <li class='dropdown'>
                <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                  <%= t('greeting') %>
                  <%= current_user.nickname %>
                  <b class='caret'></b>
                </a>
                <!-- 下拉選單 -->
                <ul class='dropdown-menu'>
                  <!-- admin 後台 -->
                  <% if current_user.admin? %>
                    <li> <%= link_to(t('admin-access'), admin_products_path) %> </li>
                    <li class="divider"> </li>
                  <% end %>
                  <!-- user 選項 -->
                  <li> <%= link_to(t('user-center'), edit_account_user_path(current_user)) %> </li>
                  <li> <%= link_to(t('user-order'), account_orders_path) %> </li>
                  <li class="divider"> </li>
                  <li> <%= link_to(t('logout'), destroy_user_session_path, method: :delete) %> </li>
                </ul>
              </li>
            <% end %>
          </ul>
          <!-- 搜索欄 -->
          <%= form_tag search_products_path, :method => :get, class: "navbar-form pull-right" do %>
            <div class="input-group search-box">
              <input type="text" class="form-control" name="keyword" placeholder="<%= t('keywords')%>" value="<%= params[:keyword] %>">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <span><i class="fa fa-search"></i></span>
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>